In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
np.random.seed(42)
import random
random.seed(42)
# Load dataset
df = pd.read_csv("Telco.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
df.shape

(7043, 21)

In [3]:
# Convert TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Replace missing with 0 (new customers with tenure 0)
df['TotalCharges'] = df['TotalCharges'].fillna(0)

df[['TotalCharges']].describe()

       TotalCharges
count   7043.000000
mean    2279.734304
std     2266.794470
min        0.000000
25%      398.550000
50%     1394.550000
75%     3786.600000
max     8684.800000

In [4]:
# Define reference date
reference_date = pd.to_datetime("2024-12-31")

# Ensure tenure is integer
df['tenure'] = df['tenure'].astype(int)

# Create signup_date
df['signup_date'] = reference_date - pd.to_timedelta(df['tenure'] * 30, unit='D')

df[['customerID','tenure','signup_date']].head()

   customerID  tenure signup_date
0  7590-VHVEG       1  2024-12-01
1  5575-GNVDE      34  2022-03-17
2  3668-QPYBK       2  2024-11-01
3  7795-CFOCW      45  2021-04-21
4  9237-HQITU       2  2024-11-01

In [5]:
# Trial window
df['trial_start'] = df['signup_date']
df['trial_end'] = df['signup_date'] + pd.to_timedelta(14, unit='D')

# Subscription start (will adjust later based on conversion)
df['subscription_start'] = df['trial_end']

df[['customerID','trial_start','trial_end','subscription_start']].head()

   customerID trial_start  trial_end subscription_start
0  7590-VHVEG  2024-12-01 2024-12-15         2024-12-15
1  5575-GNVDE  2022-03-17 2022-03-31         2022-03-31
2  3668-QPYBK  2024-11-01 2024-11-15         2024-11-15
3  7795-CFOCW  2021-04-21 2021-05-05         2021-05-05
4  9237-HQITU  2024-11-01 2024-11-15         2024-11-15

In [6]:
users_df = df[['customerID', 'signup_date', 'Contract', 'MonthlyCharges']].copy()

users_df.columns = [
    'user_id',
    'signup_date',
    'plan_type',
    'monthly_fee'
]

users_df.head()

      user_id signup_date       plan_type  monthly_fee
0  7590-VHVEG  2024-12-01  Month-to-month        29.85
1  5575-GNVDE  2022-03-17        One year        56.95
2  3668-QPYBK  2024-11-01  Month-to-month        53.85
3  7795-CFOCW  2021-04-21        One year        42.30
4  9237-HQITU  2024-11-01  Month-to-month        70.70

In [7]:
channels = ['Organic', 'Google Ads', 'Instagram Ads', 'Referral', 'Direct']
probabilities = [0.35, 0.25, 0.15, 0.15, 0.10]

users_df['acquisition_channel'] = np.random.choice(
    channels,
    size=len(users_df),
    p=probabilities
)

users_df.head()

      user_id signup_date       plan_type  monthly_fee acquisition_channel
0  7590-VHVEG  2024-12-01  Month-to-month        29.85              Direct
1  5575-GNVDE  2022-03-17        One year        56.95          Google Ads
2  3668-QPYBK  2024-11-01  Month-to-month        53.85       Instagram Ads
3  7795-CFOCW  2021-04-21        One year        42.30            Referral
4  9237-HQITU  2024-11-01  Month-to-month        70.70       Instagram Ads

In [8]:
# Attach acquisition_channel back to main df
df['acquisition_channel'] = users_df['acquisition_channel']

def conversion_probability(channel):
    base = 0.75
    
    if channel == 'Organic':
        base += 0.05
    elif channel == 'Referral':
        base += 0.07
    elif channel == 'Instagram Ads':
        base -= 0.05
    elif channel == 'Google Ads':
        base -= 0.03
    
    return base

# Apply conversion logic
df['converted'] = df['acquisition_channel'].apply(
    lambda x: np.random.rand() < conversion_probability(x)
)

# Users who did not convert → tenure becomes 0
df.loc[df['converted'] == False, 'tenure'] = 0

df['converted'].mean()

np.float64(0.7678546074116144)

In [9]:
def realistic_cancel(row):
    # Paid churn only
    if row['Churn'] == 'Yes' and row['tenure'] > 0:
        extra_days = np.random.randint(5, 25)
        return row['signup_date'] + pd.to_timedelta(row['tenure'] * 30 + extra_days, unit='D')
    return pd.NaT

df['cancel_date'] = df.apply(realistic_cancel, axis=1)

df[['customerID','tenure','cancel_date']].head()

   customerID  tenure cancel_date
0  7590-VHVEG       0         NaT
1  5575-GNVDE       0         NaT
2  3668-QPYBK       2  2025-01-24
3  7795-CFOCW      45         NaT
4  9237-HQITU       0         NaT

In [10]:
def rebuild_status(row):
    if not row['converted']:
        return 'trial_churn'
    elif row['Churn'] == 'Yes':
        return 'canceled'
    else:
        return 'active'

df['status'] = df.apply(rebuild_status, axis=1)

df['status'].value_counts()

status
active         3962
trial_churn    1635
canceled       1446
Name: count, dtype: int64

In [11]:
subscriptions_df = df[['customerID',
                       'trial_start',
                       'trial_end',
                       'subscription_start',
                       'cancel_date',
                       'status']].copy()

subscriptions_df.columns = [
    'user_id',
    'trial_start',
    'trial_end',
    'start_date',
    'cancel_date',
    'status'
]

subscriptions_df.head()

      user_id trial_start  trial_end start_date cancel_date       status
0  7590-VHVEG  2024-12-01 2024-12-15 2024-12-15         NaT  trial_churn
1  5575-GNVDE  2022-03-17 2022-03-31 2022-03-31         NaT  trial_churn
2  3668-QPYBK  2024-11-01 2024-11-15 2024-11-15  2025-01-24     canceled
3  7795-CFOCW  2021-04-21 2021-05-05 2021-05-05         NaT       active
4  9237-HQITU  2024-11-01 2024-11-15 2024-11-15         NaT  trial_churn

In [12]:
payments_list = []

for _, row in df.iterrows():
    
    # Skip trial churn users
    if row['status'] == 'trial_churn':
        continue
    
    tenure = int(row['tenure'])
    
    for month in range(tenure):
        payment_date = row['trial_end'] + pd.to_timedelta(month * 30, unit='D')
        
        # Stop if payment exceeds cancel_date
        if pd.notna(row['cancel_date']) and payment_date > row['cancel_date']:
            break
        
        payments_list.append({
            'user_id': row['customerID'],
            'amount': row['MonthlyCharges'],
            'payment_date': payment_date,
            'status': 'success'
        })

payments_df = pd.DataFrame(payments_list)

payments_df.shape

(174752, 4)

In [13]:
events_list = []

event_types = ['login', 'template_created', 'document_shared', 'premium_feature_used']

for _, row in df.iterrows():
    
    if row['status'] == 'trial_churn':
        continue
    
    tenure = int(row['tenure'])
    
    for month in range(tenure):
        
        # Engagement decay probability
        if month == 0:
            active_prob = 1.0
        elif month == 1:
            active_prob = 0.85
        elif month == 2:
            active_prob = 0.75
        elif month == 3:
            active_prob = 0.65
        else:
            active_prob = 0.55
        
        # Decide if user active this month
        if np.random.rand() > active_prob:
            continue
        
        # Event intensity
        if row['status'] == 'active':
            events_count = np.random.randint(6, 12)
        else:
            events_count = np.random.randint(2, 6)
        
        for _ in range(events_count):
            event_time = row['signup_date'] + pd.to_timedelta(
                month * 30 + np.random.randint(0, 28),
                unit='D'
            )
            
            if pd.notna(row['cancel_date']) and event_time > row['cancel_date']:
                continue
            
            event_name = np.random.choice(
                event_types,
                p=[0.45, 0.25, 0.2, 0.1]
            )
            
            events_list.append({
                'user_id': row['customerID'],
                'event_name': event_name,
                'event_time': event_time
            })

events_df = pd.DataFrame(events_list)

import random

trial_users = subscriptions_df[
    subscriptions_df["status"] == "trial_churn"
]["user_id"].tolist()

trial_events = []

for user in trial_users:
    num_events = random.randint(3, 15)

    for _ in range(num_events):
        trial_events.append({
            "user_id": user,   # matches events_df
            "event_name": random.choice(["login", "view_page", "trial_start"]),
            "event_time": np.random.choice(events_df["event_time"])
        })

trial_events_df = pd.DataFrame(trial_events)

events_df = pd.concat([events_df, trial_events_df], ignore_index=True)

events_df.shape

(798816, 3)

In [14]:
# Monthly marketing spend from 2021 to 2024

months = pd.date_range(start="2021-01-01", end="2024-12-01", freq='MS')

marketing_data = []

channel_base_spend = {
    'Organic': 2000,
    'Google Ads': 10000,
    'Instagram Ads': 7000,
    'Referral': 3000,
    'Direct': 1000
}

for month in months:
    for channel in channels:
        spend = channel_base_spend[channel] + np.random.randint(-500, 1500)
        marketing_data.append({
            'channel': channel,
            'month': month,
            'spend': max(spend, 0)
        })

marketing_spend_df = pd.DataFrame(marketing_data)

marketing_spend_df.shape

(240, 3)

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:YOUR_PASSWORD@localhost/saas_clean")

In [16]:
users_df.to_sql(
    name='users',
    con=engine,
    if_exists='replace',
    index=False
)

7043

In [17]:
subscriptions_df.to_sql(
    name='subscriptions',
    con=engine,
    if_exists='replace',
    index=False
)

7043

In [18]:
marketing_spend_df.to_sql(
    name='marketing_spend',
    con=engine,
    if_exists='replace',
    index=False
)

240

In [19]:
payments_df.to_sql(
    name='payments',
    con=engine,
    if_exists='replace',
    index=False
)

174752

In [20]:
chunk_size = 50000

# First chunk → replace
events_df.iloc[0:chunk_size].to_sql(
    name='events',
    con=engine,
    if_exists='replace',
    index=False
)

# Remaining chunks → append
for i in range(chunk_size, len(events_df), chunk_size):
    events_df.iloc[i:i+chunk_size].to_sql(
        name='events',
        con=engine,
        if_exists='append',
        index=False
    )
    print(f"Inserted rows {i} to {i+chunk_size}")

Inserted rows 0 to 50000
Inserted rows 50000 to 100000
Inserted rows 100000 to 150000
Inserted rows 150000 to 200000
Inserted rows 200000 to 250000
Inserted rows 250000 to 300000
Inserted rows 300000 to 350000
Inserted rows 350000 to 400000
Inserted rows 400000 to 450000
Inserted rows 450000 to 500000
Inserted rows 500000 to 550000
Inserted rows 550000 to 600000
Inserted rows 600000 to 650000
Inserted rows 650000 to 700000
Inserted rows 700000 to 750000
Inserted rows 750000 to 800000

In [21]:
print(subscriptions_df.columns)

Index(['user_id', 'trial_start', 'trial_end', 'start_date', 'cancel_date',
       'status'],
      dtype='object')